package eventpassport;

public enum StateEnum {

    INIT, CONNECTION_OPENED, UPSTREAM_RECEIVED, DOWNSTREAM_REQ1_SENT,
    DOWNSTREAM_RESP1_RECEIVED, DOWNSTREAM_REQ2_SENT, DOWNSTREAM_RESP2_RECEIVED,
    UPSTREAM_SENT, CONNECTION_CLOSED, TEARDOWN;

}
